"
!SymInfo
represente les informations du systeme hote 
- organisation du domaine
controle les  usages de l'information
- modification interne -> liens -> groupe ...
- les informations echangées, partagées, 
-- maintient des relations

Le point conceptuel central est la différence entre une information globale / locale.
Une information atomique est donnée pour un contexte spatio-temporel fixé.

Une information exprimée en fonction du contexte est une information plus riche, à la limite de la connaissance.
ex: taille (information globale - historique - projection) vs. la mesure de la taille.
Quand on demande la taille a une personne dans un formulaire (contexte SI), on demande en fait la mesure d'une grandeur physiologique, donc variable contextuellement (temporellement principalement ici)

"
Class {
	#name : #SymbiosAbstractInfo,
	#superclass : #SymbiosObject,
	#category : #Symbios
}
